---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pve-exporter
  namespace: monitoring
spec:
  encryptedData:
    PVE_TOKEN_VALUE: AgAXlyzueh8YJm2lm1bnSN8ihUIWdUE7JgMV1e1n4LnHD8US88NzNagBpro8HqNqZBKqRqgF8SioHmJdFggsOrkKtLFP44n5KfLcFn47rEns7Aa4AsurT7C5o8RGT9qO8E1qUnOTKxYlYMxQuLn1aGA6SUG47Xks0tEY2nQpbH1LXnqqTXOUthIyR1VpTvQjgKoNgrjZW1VxXkycSgYw7YA33yMcNVFceCkz+R1rLNp03ea3HkMN8swbz64o1PGmfGcjgngmkhABDEu/drxaaWLzt/BrB1JvuYa7S0i7kxuS9bnOjFNDicYdi+OdwUNVrF0pwHVyzwkrAQSKzyxl9XSiYzDd2YCoxAK+YLig25XbadDC6FeGuKVoth6Vq9yRpbJWRadXtvd6TYmOTIBjacL4WMZWm6xlp9OTCfIIQoPCtW1qeDwtEFbzWYs8GfHk1FC6sbw0y5CxB6O5ki3A74f0CS99P2IOMGj9plvQYJuxdlsTWRX4UcwfiIfZh4Fy9avZTYjFUG6B/dW3B/OL/KvACZnCwIRU7s1o0Mrfbo6w/xLQ9GJf3onrUMfLxNru+QfB11i1SEpUsICJYqqecVw9pXj7h9a1NoCt6V4b181GeK+O2+nzsjCPVmTyFC51vvacUcHIn3ZrKneRgC26d7YCXxHP4hEGw4XFnWzTq8ci2n50v4kDMyytq5rGFg0aH4MJYGXFHvYMfxBrVY/hVaOJg+jxjUBKnLIvKtq1KJ81X7AFQ5w=
  template:
    metadata:
      name: pve-exporter
      namespace: monitoring
