---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pve-exporter
  namespace: monitoring
spec:
  encryptedData:
    PVE_TOKEN_VALUE: AgBotnykBW34n9NKsRQdO0dxll4Wi5+7PgM/Q7CNhRdCwXud5OPS3tCdVw/ugroZC340BZ5ZZfXNUrTC6sXqBQvIVQ9C2DdyyZKJTOnqAhYhfjrZlSHyWMHrX6bSXZxl0BsZr1reTJHqr19ZxcLTrpmoihCnHDo38cm9m2yCMDUMYbxc11CjB4jXMQlNETFrpBzXbCYUpee+NpWb75qP095GGHCSbXSgHVEF+Fbao1ULg2YdIkO8VUkIxw85QNf89Oh+WXEJmTvB0IlGTJ5sXW9xAkLH1KEHNCQyIPOSz1F9Hi/hWDcPx8/Lh/nQYBnWUQto0KJ06c3A8R8WhJoVKSNFpYy2ItW8smYlULtxuuFAixHwEe50ltlR6Wmz21HA3m3RHbOGdkz4xDr/AEGR4TTh1zyHXo/B6TBDKTAh7+pxSASD3ljPOEaQ7+qlgrAXGwTuSx9tjP5xrZ00mWK2MwRcMfUTcd11Ha5nz0W60zIuDCnIA+mxySDom4Y/vmlqItmfYQVEuIqe22J1hnwySfyxfDbMvvKcDpmuWf4RP8z0o2FcDYyXtTGwAjMQZ+RCnG3RLdwn8LpW977efsg2GPi9+cxggJ8Ux/BOUEjHlODXYfoZGg9KzVQaqDu6cTAWf3VsweakuXjRsJOjBtsvc1wPXhnndIo0ygaTsuJeBRv1fZ6Y8dG5T+Zph02C9pUAqNAGXpUS1hMWdGgzeha6YlQRqEy+4wlTIYUu6TPTkzjcHyCwDs8=
  template:
    metadata:
      name: pve-exporter
      namespace: monitoring
