---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgCm8ouFu0R0WVwIVHDE9YtXzObOGtWR0CzTWx29JFX/Szq3rdMGBYkZJ/o7RWyYK8DIr96SLuJNd1gAGh742JpHzhZAY1KoUkCfWpq+Se2XLmvTgV25+QQ6vzm/2VXE8aN8YioBtA8xpoUUSfkzKDnhpYOc/+AtUxpy0XDErmUTgzK/7BtxxL04V7O3GnADvtvDN787t2QrfazMigD8xgZhQODtBKioxpdLfTghoLu4ch9DNfLe/6BUeKsAQWF/zqEwCfODT6mKdQv5LbXDgBdLSuJBbN5vsyCFe3iVXr9Wy0XKJKU3Dw0+MbMeNatIUrkqWI/mL8qz2EQm0fsqCKd5zciH5nnTRItDj1qrzLHWyTfpCUpsq7nU52L/tkV+/01CjD29RD9VR3Urcl9P1NILuryEwN0O1DESgBxOZhQPFSrUJnDqzwLK1akoO6bw2UNlj3xUhMdgpIEyNR6D8ojHEhQLmutp2mQuLag2o/yDU2CutPps3ZvIF14ShFHKuWVa7mJRQG6l08o7N9kZVgElejoTDhPv+jKCGQ5joWtP+2SxYKrsg88lpAfstHN74j2SskUdUf8kWi9e7DZ/n5BQ+UjQGCArQiu+mnFAIdYu4iGD9bUuav2+iD8IyGRlIjAuEWtJW9+7KXDKtvkynwPSzh4zym3po3CIjx6h7sm3uT1L6BVZyFAQ6GiLSN8LTRxUsvCdWc8Flho+SU5d7l3yuh0UCw==
    admin-user: AgAQSPiQAz7CigS4V5VVBsIyrjnhw+AYwts1dmtL2FG4X/icyM3r3qUx7Fn5+oDthvfwC4xMra8GiJ9kBaZIat0AYbC2y62bVylkTgIFri03CBiYLK15jCkoRYD/JV8A+FRqzRtZ3NJed7InhB+Y2zxnOtTp1uZltDE3Vmd2O0a825rm6VwfkqG/KgPB5v19BBeiW/EJjdH60cB+XCboiMod9/bSQTLdKC9nm7t10GhTBTK+qbFjY58qu/wgd7twoFpVyhMtAhctNlsG/1ENrw4V32fosBIMAJ35BQsosjp2bdx4m/M6qenRed0CEQUBeK5gD4GBJLHk8PWNqGLNFTlTAXZCxYDqEz2J9mwJZgOCvoRrT1sWkk5Nrv0NyiC7r0FZfVTY31QJlIoyTQ+pr0IfsIWUra/6+H/zZp60kCmqvBebX2BG1UZhpDgo/kmq/YOR8MMq6z3PtCtN3OKif7TQNAQwiDsTaQVBCtPDj15obBKA6+c+fRid0JGxKNNwDCg6JXb528P3A6kQ7kPraMPTCWAjwf4lqBY7YA3g8Z9puiABmvzAVFptoPYPWUCDzsTa+nk482X5cX9WYdihLyjBPo5CPPDCu6shTTh7lBsqe97EJwaHNs8RgmPyk/A2BdDVU9zJThcZ7oa5gSINFRD8LLjWhSuKZ6URtYO+Wp0+f8EEuBbln+sIAns77p8g6JJg3x2Btw==
  template:
    metadata:
      name: grafana-admin
      namespace: monitoring
