apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflared
  namespace: base-apps
  labels:
    app: cloudflared
spec:
  replicas: 2 # Run 2 replicas for high availability
  selector:
    matchLabels:
      app: cloudflared
  template:
    metadata:
      labels:
        app: cloudflared
    spec:
      containers:
      - name: cloudflared
        image: cloudflare/cloudflared:latest
        args:
        - tunnel
        - --no-autoupdate
        - run
        env:
        - name: TUNNEL_TOKEN
          valueFrom:
            secretKeyRef:
              name: cloudflared-creds
              key: TUNNEL_TOKEN 
        resources:
          requests:
            cpu: 10m
            memory: 64Mi
          limits:
            cpu: 100m
            memory: 128Mi
