---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflared-creds
  namespace: base-apps
spec:
  encryptedData:
    TUNNEL_TOKEN: AgCBpqp3IptIiLJKVqwsXuQwVQoN4l6IYtUfskd17TwhMPpN3cRdqxZlcrDJJpRsSpHTNCzzJEzuQey7ozdFKTi76AjowBxtAY7CkkYPIzGxnrR9wyXge6ZW3YXs5f4JVtMKwTfgTCKN7PH8Hw8SHfc05fTZyM2IblvIQ3SL5EJrpUFUUIzFCwXaz8GUBPRaI0M+UoJw8YjU9KSq/UJwlJ58C930STgmmoBeDlx5CyBHOibZxP8ZBdHpDGd2HhC3qB4UqQMxwAPFqVz/CJq2oAu4J9+ggRSM9Jl0HEXHyqlY+ynaVSg58sFoU7q3WjTU+MgmW2s+WkiFloA8R7WCzHstfijuCEBvyqE3v4st115V1LGYoEyuuRcINaIhE1HwZ87Q+g8yhCs4fmUr9PDKspKKP7p0XVct0ltBoXVtTOCWipnKmNJLyvm+h8FNnglhPjBrOk9sEiGKtdIjeGLnnLyIOWNYVEfM6APoVjqK1So6hUw/N9Hh2kzF3Crwn70yzODb3DqWoc4eqfrJHBmUIv3AKUqawFE6yq9FUDZqly1KA9aMImUb8866x/UjaVx3sV1WC3Q3oCv5awccj9ePWqFITnMAkDtipy+3QMNVb36u/PvQVY2zfictLXMtAPEQ/QuokbaNFY7bkQQCR5ZKtuMrXgyyIj8JmJb4tevoI4z/YEk1RyAsrYRGFT0z0oJG48kF2eDI8m0T4ICqVfa/szNBNvLyyK3O8GwB6k3l3MZa+EzeeQqMJiU/ZDJiRoBK8CmiHD5yfxUrZ/WFMuxJ0dXpHLhVjhJbob5gtO60WjIK2Rw5vGp3DCjrSVmEczw5+JRPGUjYZHP6aTtpXPGg/rsr9UXOVD4qaf1/tkELsQScmKHJ933YyylRcAKKqanzEiR7E4QRiUN6dzrdzlqIB5wHz3r1XOhlpuaROkEvQazmu/wcNI6iFuRm
  template:
    metadata:
      name: cloudflared-creds
      namespace: base-apps
    type: Opaque
