---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflared-credentials
  namespace: base-apps
spec:
  encryptedData:
    credentials.json: AgDEY9EsygTwBpVwuIlTVX9lpwafsSOzy5cIuUPBLGuRcQOtpcZZzL4YbSPAGQMWcGVMp+yOuUzcbZIiZz3Xm4lMxGQiCl2gLnK23Booa3bjytFFKua+Wdv4ALcyv3Wp2FP6Qfx5Skr/fkwIU38yDrNuRBJAvVLoz5JRjtAFTbssaa6rkUNtL3p1TwWAiNKDEtVO0EjiUOYwxi2ClNMbtGon3PX3RQNCoa8UHoiNL8KFuKc3AO0zzr/gSrA8o0O+z/iXu6iRqDqV+JGIbQ9pbQSVKrT/ion5gsfhcHnXEXWyVeud9BSiuAjcSmwhrkzf8xH7fDa/aze9IwcHgz5Ze0rxKCD9Q7LWhgpOilhPD2xgfp7HwrMDD64JltWe8ernU7/RH284aaYi0Vo0UwjwpEiUau3effHMV1YgquQ9qAoN9pnk9mbytopCcuR6B+/o4U66W246WZ1ndtfslhRrGqFRjZXJyxFutqVz+2aJVEC5bebp3+47Je4v7c3msCCj1zhHCr+JkAxel43Kx20yNe9g92o/2vcrOiythYYCMdmHcxnzkZ3mIrxRzcbT6YGxyavIasq1/UJAdAzdgN1ex1n2nwS2Htv4YXZh9HbeLZ1PK2kb8aD2IVHpkwUtsR6uwV/vUxQszu++xh94n1/l2J8dtASpV8nKl4a6K0Iij60r6xjFh6f3+eMf1kIimgMgbWDBYzzRqN1ex+yiAsGhPdMPcuhlYX+7Lq/1VWAGXf5vSzmBfe6rXG4Cg/iV7fhPuh5AWgfxRa+27P8Og8QWsx4+JN+qA5tuj6SUV50CDiCpe5gtvYmVR/78pPMpLaUIzPtbpQKv541NXfF4apd6MRCMdOHWj33I6ElwOhidzFxP9aj6zb+6LgTHtSQe8LM2/HFRXlG9lc4Y//AUM1bYzKFXJ/tO6jZRMCRPIw==
  template:
    metadata:
      name: cloudflared-credentials
      namespace: base-apps
