---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflared-creds
  namespace: base-apps
spec:
  encryptedData:
    TUNNEL_TOKEN: AgBcGgbvCKKsrjmrPzMeaLtQwHWdx1FpcdwtYru+KSyNCLpMSeQqZ4rQEGVUZ4huceiv2DkrEkn0RCylbwFTyMEF15hh5hVmvhgo/hdIUZ1ZTiuP3084IsmSWwh6laq+MYiuhOVR14Wr+i0UF9VY3A2XFI4Axb+Xy8kXWWbHiAm6/tJUcUKAD4jRKF3XF9D2voely6+Cy6Mi9nlWbSnHVytUCJif80I4OAFsEgoEFPH4Y/YP1E8GnJKJcCcNnqmgjZYqCEkK3NVzEiVjb3WIWQyUkYjPtEvOT5/FQUnpd6MCxY7Bt77f+CrH2BUspnm+qPB1zFEBnCICoEQFFtcMdmta/QUYOQBRaDDvjQJ5nEFkHNMqCG1rHupX8CtWRmJqk9W+jT4SvP1Uh+Yccrku4skymI/ukTnnj/1lc+iBUBQ27QXAqYgFkrXVeLRgG1EPxpu79SwaEP4fOM7kQJVlD2rUafJJ5Jjf0nopWqxW9/WJ9pYN2CMIDwVfjoIVtYJj/aX6stebIrLB8kSRMRuKnnKSV6aE8+hGycO7+Hl90oQK95JWUd/DnAfs169ESa6pADMPq5mFUC/98464cvc4+79i1viZUuhxm9p9yLk2mFaeP0T2nHJPF85GHTBIXAbEi90sLAh3fSs6mtZY83J9ZPiyW+fyLV8ohVR4nDzEKfk/i+JqYHq7hhMUG905qEhrVNKFhTd4wwDWHSf1C6d+uy9DZneUtKbZ069GYRnnUGpSPww9jb5MqtkztQkak9C8FMAE4r0MPjE0Xfquu6T+lLdeacTqoBjzSpNwYJB0CCLZYsdAztpHj0KwDWY5N5z8QfmHMdp7RxgbtvDMOaroWoMkiwXhIsVAUuvhuj4q06EfM5XW9E6wYWvbbxHqAu4oNBoQfj/7YmCgBgvdMGDti2Lri9ZT3Ah/J6BtES/bBMklE0kNlxrEbxTV
  template:
    metadata:
      name: cloudflared-creds
      namespace: base-apps
